language: en
pipeline: 
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "RegexFeaturizer"
  - name: "DucklingHTTPExtractor"
    url: "http://localhost:8000"
  - name: "SpacyEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "SklearnIntentClassifier"
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
  - name: MappingPolicy
  - name: FormPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.4
    core_threshold: 0.3
    fallback_action_name: action_default_ask_rephrase
