version: '3.0'
services:
  rasa:
    image: horusrasaregistry.azurecr.io/rasa/rasa:custom2
    ports:
      - 80:5005
    networks: 
      - app_net
    
  action_server:
    image: horusrasaregistry.azurecr.io/rasa/rasa-sdk:custom2
    expose: 
      - 5055
    networks: 
      - app_net

networks: 
  app_net:
