version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command: >
      run 
      --enable-api
      --endpoints endpoints.yml
      --cors "*" 
    
  action_server:
    image: rasa/rasa-sdk:latest
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions
    # command: >
    #   run
    #   actions
  