version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest
    ports:
      - 80:5005
    volumes:
      - ${WEBAPP_STORAGE_HOME}:/app
    command: >
      run 
      --enable-api
      --endpoints endpoints.yml
    
  action_server:
    image: rasa/rasa-sdk:latest
    volumes:
      - ${WEBAPP_STORAGE_HOME}:/app/actions 
  