version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest
    ports:
      - 80:5005
    volumes:
      - ./:/app
    command: >
      run 
      --enable-api
      --endpoints endpoints.yml
      --cors "*" 
    
  action_server:
    image: rasa/rasa-sdk:latest
    volumes:
      - ./actions:/app/actions
  