version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest
    ports:
      - 80:5005
    volumes:
      - ${WEBAPP_STORAGE_HOME}:/app
    restart: always
    command: >
      run 
      --enable-api
    
  action_server:
    image: rasa/rasa-sdk:latest
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}:/app/actions
  