language: de
pipeline: supervised_embeddings
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
- name: FormPolicy
- name: FallbackPolicy
  nlu_threshold: 0.4
  core_threshold: 0.3
  fallback_action_name: utter_did_not_understand
